# Generated by Django 5.0.1 on 2024-01-04 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advocate',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
