# Generated by Django 5.0.1 on 2024-01-05 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_advocate_id_alter_advocate_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supreme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.advocate')),
            ],
        ),
    ]
