# Generated by Django 5.0.1 on 2024-01-06 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0004_rename_question_supreme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supreme',
            name='advocate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supreme_advocates', to='framework.advocate'),
        ),
    ]
