# Generated by Django 5.0.1 on 2024-01-06 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0005_alter_supreme_advocate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supreme',
            name='advocate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='framework.advocate'),
        ),
    ]
